'use strict'

const Undertaker = require('undertaker')
const vinylFs = require('vinyl-fs')
const watch = require('glob-watcher')

class Gulp extends Undertaker {
  constructor () {
    super()
    // Bind the functions for destructuring
    this.watch = this.watch.bind(this)
    this.task = this.task.bind(this)
    this.series = this.series.bind(this)
    this.parallel = this.parallel.bind(this)
    this.registry = this.registry.bind(this)
    this.tree = this.tree.bind(this)
    this.lastRun = this.lastRun.bind(this)
    this.src = this.src.bind(this)
    this.dest = this.dest.bind(this)
    this.symlink = this.symlink.bind(this)
  }

  src = vinylFs.src
  dest = vinylFs.dest
  symlink = vinylFs.symlink
  watch (glob, conf, task) {
    if (
      typeof conf === 'string' ||
      typeof task === 'string' ||
      Array.isArray(conf) ||
      Array.isArray(task)
    ) {
      throw new Error(`watching ${glob}: watch task has to be ` +
        'a function (optionally generated by using gulp.parallel ' +
        'or gulp.series)')
    }

    if (typeof conf === 'function') {
      task = conf
      conf = {}
    }

    conf = conf || {}

    let func
    if (typeof task === 'function') {
      func = this.parallel(task)
    }

    return watch(glob, conf, func)
  };

  static Gulp = Gulp
}

module.exports = new Gulp()
